"""FR-CR-05-136 — match a meeting recording to its real
calendar event title via Apps Script proxy + LLM-pass.

Why Apps Script (not service-account):
- Operator pinned: «через Apps Script потому что я подключу
  потом другой токен где у меня не будет возможности сделать
  сервис аккаунт потому что там надо биллинг подключить — это
  сложно».
- Apps Script Web App runs as the operator's Google user; no
  GCP project / billing required for Calendar read.

Architecture (split):
- Apps Script side (`docs/apps_script/calendar_proxy.gs`):
  exposes a `doGet` Web App endpoint with a shared-token guard;
  returns Calendar events between `from` / `to` ISO timestamps.
- Python side (this module): HTTPs the Apps Script URL, runs
  an LLM-pass to pick the best match against the meeting's
  agenda, formats the canonical title `DD/MM - <event title>`.

Pipeline integration: the new `_step_match_calendar_title`
runs AFTER `_step_detailed_summary` (we have the agenda) and
BEFORE `_step_match_counterparties` (so the canonical title
can flow into the doc + short summary header).
"""
from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timedelta, timezone
from typing import Any

from app.logging_setup import get_logger
from app.services.trace_log import trace_event

log = get_logger(__name__)


CALENDAR_MATCH_SYSTEM = """\
You match a recorded meeting to the calendar event that the
recording most likely captured.

Input (in the user prompt):
- `agenda`: a few-sentence excerpt from the meeting's detailed
  summary (operator-generated by the previous LLM-pass).
- `candidates`: a numbered list of calendar events that
  occurred within ±N minutes of the recording's start time.
  Each entry has `title`, `attendees`, optional `description`.

Pick the candidate index whose TITLE + ATTENDEES + (optional)
DESCRIPTION best match the agenda content. If none plausibly
match (e.g. all candidates are unrelated or the agenda is
generic), return null.

Output as a JSON object:
  `{"picked_index": <int|null>, "reason": "<short>"}`

Rules:
1. Index is the 1-based position from the input numbered list,
   or null when no plausible match.
2. Don't invent a title — only pick from the provided
   candidates.
3. Internal-only meetings («letter check», «sync», «letuchka»)
   without a clear agenda match → null.
4. The selected event MUST have temporal proximity AND topical
   relevance — both, not just one.
"""


def fetch_calendar_events_via_api(
    meeting_dt: datetime,
    *,
    window_minutes: int,
    credentials_factory: Any,
    calendar_id: str = "primary",
) -> list[dict[str, Any]]:
    """FR-CR-05-144 — fetch Calendar events via direct Google
    Calendar API (replaces the Apps Script proxy of FR-CR-05-136).

    `credentials_factory` is a callable returning a refreshed
    `google.oauth2.credentials.Credentials` (we delegate the
    refresh to the OAuth store, same as Sheets/Docs/Tasks).
    Returns events in the same shape as
    `fetch_calendar_events_around` (`{title, start, end,
    attendees, description}`) so downstream LLM-pass + format
    code is unchanged.

    Failures NEVER raise — empty list on auth fail, network
    fail, or any HttpError. Operator-pinned.

    FR-CR-05-152 — `calendar_id` accepts a COMMA-SEPARATED list
    of calendar ids. Each is queried independently; results are
    merged and deduplicated by event id. Operator regression:
    «Fundraising daily» lives on `c_15b48…@group.calendar…`,
    «Sculptor» on primary, «Чайная церемония» on personal — a
    single calendar is too narrow. Operator-pinned: «надо все
    кроме личного» (multi-calendar with the personal one
    excluded). Pass calendar id list as
    `GOOGLE_CALENDAR_ID=primary,c_xxxx@group...,c_yyyy@group...`.
    """
    if meeting_dt is None or credentials_factory is None:
        return []
    if meeting_dt.tzinfo is None:
        meeting_dt = meeting_dt.replace(tzinfo=timezone.utc)
    delta = timedelta(minutes=int(window_minutes))
    time_min = (meeting_dt - delta).isoformat()
    time_max = (meeting_dt + delta).isoformat()
    try:
        creds = credentials_factory()
    except Exception as e:  # noqa: BLE001
        log.warning("calendar_match_api_credentials_failed", error=str(e))
        return []
    if creds is None:
        log.info("calendar_match_api_no_credentials")
        return []
    try:
        from googleapiclient.discovery import build
        from googleapiclient.errors import HttpError
    except ImportError:
        log.warning("calendar_match_api_googleapiclient_missing")
        return []
    # Parse comma-separated list, drop blanks.
    cal_ids = [
        c.strip() for c in (calendar_id or "primary").split(",") if c.strip()
    ] or ["primary"]
    try:
        service = build(
            "calendar", "v3", credentials=creds,
            cache_discovery=False,
        )
    except Exception as e:  # noqa: BLE001
        log.warning(
            "calendar_match_api_unexpected_error",
            calendar_ids=cal_ids, error=str(e),
        )
        return []
    out: list[dict[str, Any]] = []
    seen_event_ids: set[str] = set()
    for cid in cal_ids:
        try:
            resp = service.events().list(
                calendarId=cid,
                timeMin=time_min, timeMax=time_max,
                singleEvents=True, orderBy="startTime",
                maxResults=50,
            ).execute()
        except HttpError as e:  # noqa: BLE001
            log.warning(
                "calendar_match_api_http_error",
                status=getattr(e, "status_code", None),
                calendar_id=cid,
            )
            continue
        except Exception as e:  # noqa: BLE001
            log.warning(
                "calendar_match_api_unexpected_error",
                calendar_id=cid, error=str(e),
            )
            continue
        for ev in (resp.get("items") or []):
            if not isinstance(ev, dict):
                continue
            ev_id = ev.get("id") or ""
            # Same event can appear in multiple calendars (when
            # both host + attendee calendars are queried). Keep
            # only the first occurrence by stable id.
            if ev_id and ev_id in seen_event_ids:
                continue
            if ev_id:
                seen_event_ids.add(ev_id)
            out.append({
                "id": ev_id,
                "title": ev.get("summary") or "",
                "start": (ev.get("start") or {}).get("dateTime")
                         or (ev.get("start") or {}).get("date") or "",
                "end": (ev.get("end") or {}).get("dateTime")
                        or (ev.get("end") or {}).get("date") or "",
                "attendees": ev.get("attendees") or [],
                "description": ev.get("description") or "",
                # FR-CR-05-167 — keep both `organizer` and
                # `creator`. On shared / Workspace calendars
                # `organizer.email` is sometimes rewritten to the
                # calendar owner (even when somebody else created
                # the event). `creator.email` keeps the original
                # author, so the agenda runner checks both before
                # accepting an event as «hosted by operator».
                "organizer": ev.get("organizer") or {},
                "creator": ev.get("creator") or {},
                "_calendar_id": cid,  # for trace / debugging
            })
    return out


def fetch_calendar_events_around(
    meeting_dt: datetime,
    *,
    window_minutes: int,
    apps_script_url: str,
    shared_token: str,
    timeout_seconds: float = 15.0,
) -> list[dict[str, Any]]:
    """HTTP GET the Apps Script proxy for events within
    ±`window_minutes` of `meeting_dt`. Returns the list of
    event dicts (`{title, start, end, attendees, description}`)
    or an empty list on any failure.

    Operator-pinned: failures NEVER cascade into the pipeline.
    """
    if not apps_script_url or not shared_token or meeting_dt is None:
        return []
    if meeting_dt.tzinfo is None:
        meeting_dt = meeting_dt.replace(tzinfo=timezone.utc)
    delta = timedelta(minutes=int(window_minutes))
    qs = urllib.parse.urlencode(
        {
            "token": shared_token,
            "from": (meeting_dt - delta).isoformat(),
            "to": (meeting_dt + delta).isoformat(),
        }
    )
    url = f"{apps_script_url}?{qs}"
    try:
        with urllib.request.urlopen(url, timeout=timeout_seconds) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        log.warning(
            "calendar_match_apps_script_http_error",
            status=e.code, url=apps_script_url,
        )
        return []
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
        log.warning(
            "calendar_match_apps_script_failed",
            error=str(e), url=apps_script_url,
        )
        return []
    if not isinstance(payload, dict):
        return []
    if payload.get("error"):
        log.warning(
            "calendar_match_apps_script_returned_error",
            error=payload.get("error"),
        )
        return []
    events = payload.get("events") or []
    return [e for e in events if isinstance(e, dict)]


def _render_candidates(events: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    for i, ev in enumerate(events, start=1):
        attendees = ev.get("attendees") or []
        att_emails = ", ".join(
            (a.get("email") or "")[:60]
            for a in attendees if isinstance(a, dict)
        )[:300]
        desc = (ev.get("description") or "").strip()[:200]
        lines.append(
            f"  {i}. title: {ev.get('title') or '<untitled>'}\n"
            f"     attendees: {att_emails or '—'}\n"
            f"     description: {desc or '—'}\n"
            f"     start: {ev.get('start') or ''}"
        )
    return "\n".join(lines)


def match_calendar_event_to_meeting_via_llm(
    *,
    agenda: str,
    events: list[dict[str, Any]],
    llm_backend: Any,
    model: str,
    reasoning_effort: str | None = None,
) -> dict[str, Any] | None:
    """Ask the LLM to pick the best matching calendar event.

    Returns `events[picked_index-1]` on a clear pick, ``None``
    when the LLM declines or the call fails. Never raises.
    """
    if not agenda or not events:
        return None
    user_prompt = (
        "agenda:\n"
        + (agenda or "")[:5000]
        + "\n\ncandidates:\n"
        + _render_candidates(events)
        + "\n\nReturn JSON with picked_index + reason."
    )
    try:
        text = llm_backend.complete_text(
            system_prompt=CALENDAR_MATCH_SYSTEM,
            user_prompt=user_prompt,
            model=model,
            reasoning_effort=reasoning_effort,
            response_format={"type": "json_object"},
        ) or ""
    except Exception as e:  # noqa: BLE001
        log.warning("calendar_match_llm_failed", error=str(e))
        return None
    try:
        result = json.loads(text) if text else {}
    except json.JSONDecodeError:
        log.warning(
            "calendar_match_json_parse_failed",
            text_preview=(text or "")[:200],
        )
        return None
    idx = result.get("picked_index")
    if idx is None or not isinstance(idx, int):
        return None
    if idx < 1 or idx > len(events):
        log.info(
            "calendar_match_picked_invalid_index",
            picked_index=idx, candidate_count=len(events),
        )
        return None
    return events[idx - 1]


def format_canonical_title(meeting_dt: datetime, picked_title: str) -> str:
    """`DD/MM - <picked_title>` — operator-pinned shape
    («30/04 - US Innovative Technology / TWG Globa»)."""
    if not picked_title:
        return ""
    if meeting_dt.tzinfo is None:
        meeting_dt = meeting_dt.replace(tzinfo=timezone.utc)
    return f"{meeting_dt.strftime('%d/%m')} - {picked_title.strip()}"


def match_and_format_title(
    *,
    meeting_dt: datetime,
    agenda: str,
    window_minutes: int,
    llm_backend: Any,
    model: str,
    reasoning_effort: str | None = None,
    apps_script_url: str | None = None,
    shared_token: str | None = None,
    api_credentials_factory: Any | None = None,
    api_calendar_id: str = "primary",
    trace_source: str | None = None,
    trace_recording_id: str | None = None,
) -> str | None:
    """End-to-end: fetch + match + format. Returns the new
    canonical title, or ``None`` when no match (caller keeps
    the original title).

    Two backend paths (FR-CR-05-144 superseded FR-CR-05-136):
      - When `api_credentials_factory` is given, fetch via
        direct Google Calendar API.
      - Else when `apps_script_url` is given, fall back to the
        Apps Script proxy.
      - Else: no-op (returns None).
    """
    events: list[dict[str, Any]] = []
    if api_credentials_factory is not None:
        events = fetch_calendar_events_via_api(
            meeting_dt,
            window_minutes=window_minutes,
            credentials_factory=api_credentials_factory,
            calendar_id=api_calendar_id,
        )
    elif apps_script_url:
        events = fetch_calendar_events_around(
            meeting_dt,
            window_minutes=window_minutes,
            apps_script_url=apps_script_url,
            shared_token=shared_token or "",
        )
    if trace_source:
        trace_event(
            source=trace_source, recording_id=trace_recording_id,
            event="calendar_match_events_fetched",
            count=len(events),
            sample=[{"title": e.get("title"), "start": e.get("start")}
                    for e in events[:5]],
        )
    if not events:
        return None
    picked = match_calendar_event_to_meeting_via_llm(
        agenda=agenda,
        events=events,
        llm_backend=llm_backend,
        model=model,
        reasoning_effort=reasoning_effort,
    )
    if trace_source:
        trace_event(
            source=trace_source, recording_id=trace_recording_id,
            event="calendar_match_llm_picked",
            picked_title=(picked or {}).get("title"),
            candidate_count=len(events),
        )
    if not picked:
        return None
    return format_canonical_title(meeting_dt, picked.get("title") or "")


__all__ = [
    "CALENDAR_MATCH_SYSTEM",
    "fetch_calendar_events_around",
    "fetch_calendar_events_via_api",
    "match_calendar_event_to_meeting_via_llm",
    "format_canonical_title",
    "match_and_format_title",
]
